version: 0.2
phases:
  install:
    commands:
      - ls -la
  pre_build:
    commands:
      - echo "pre_build"
  build:
    commands:
      - echo "build"
      - aws s3 ls
  post_build:
    commands:
      - echo "post_build"